name: build mod manager

on:
  push:
    branches:
      - "master"
  release:
    types:
      - "published"

permissions:
  contents: write

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare dist folder
        run: |
          if (Test-Path dist) { Remove-Item dist\* -Force }
          else { New-Item dist -ItemType Directory }

      - name: Build cx_Freeze files
        run: python setup.py build

      - name: Generate NSIS file list and installer script
        run: python generate_nsis_filelist.py

      - name: Install NSIS
        run: choco install nsis -y

      - name: Build NSIS installer
        run: makensis installer.nsi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe

      - name: Upload to release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
