name: build mod manager

on:
  push:
    branches:
      - "master"
  release:
    types:
      - "published"

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.11.9"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-latest
            target: macos
          - os: ubuntu-latest
            target: linux
    runs-on: ${{ matrix.settings.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Setup development virtual environment
        run: uv sync --frozen

      - name: Run tests
        run: uv run python -m unittest discover tests

      - name: Setup production virtual environment
        run: uv sync --frozen --no-dev

      - name: Build cx_Freeze files
        run:  uv run cxfreeze build

      - name: Upload zip artifact
        uses: actions/upload-artifact@v6
        with:
          name: spacehaven-modloader-b${{ github.run_number }}-${{ matrix.settings.target }}
          path: build/

  build-windows:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Setup development virtual environment
        run: uv sync --frozen

      - name: Run tests
        run: uv run python -m unittest discover tests

      - name: Setup production virtual environment
        run: uv sync --frozen --no-dev

      - name: Build cx_Freeze files
        run:  uv run cxfreeze build

      - name: Upload zip artifact
        uses: actions/upload-artifact@v6
        with:
          name: spacehaven-modloader-b${{ github.run_number }}-windows
          path: build\

      - name: Build installer
        uses: ./.github/actions/build-nsis
        with:
          generator-cmd: |
            uv run python generate_nsis_filelist.py
          nsi-file: installer.nsi

      - name: Upload installer
        uses: actions/upload-artifact@v6
        with:
          name: spacehaven-modloader-b${{ github.run_number }}-setup
          path: dist/*.exe

      - name: Upload to release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*.exe
